// Import FontAwesome icons for centralized management
import {
  faArrowLeft,
  faTrash,
  faPlus,
  faEdit,
  faEye,
  faSearch,
  faSun,
  faMoon,
  faBars,
  faTimes,
  faHome,
  faUser,
  faUsers,
  faCog,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faArrowRight,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faCalendar,
  faClock,
  faMapMarkerAlt,
  faEnvelope,
  faPhone,
  faSync,
  faFilter,
  faSort,
  faSave,
  faBan,
  faSignOutAlt,
  faSignInAlt,
  faEyeSlash,
  faUserCog,
  faUserEdit,
  faUserPlus,
  faUserMinus,
  faUserCheck,
  faUserTimes,
  faUserShield,
  faUserGraduate,
  faUserTie,
  faUserFriends,
  faUserSecret,
  faUserNinja,
  faUserAstronaut,
  faUserDoctor,
  faUserNurse,
  faUserGear,
  faCopyright,
  faPalette,
  faTree,
  faBuilding,
  faSeedling,
  faMusic,
  faSnowflake,
  faEllipsisVertical,
  faAnglesLeft,
  faAngleLeft,
  faAngleRight,
  faAnglesRight,
  faDollarSign,
  faCreditCard,
  faCoins
} from '@fortawesome/free-solid-svg-icons';

import { faLinkedin } from '@fortawesome/free-brands-svg-icons';

// Re-export for external use
export {
  faArrowLeft,
  faTrash,
  faPlus,
  faEdit,
  faEye,
  faSearch,
  faSun,
  faMoon,
  faBars,
  faTimes,
  faHome,
  faUser,
  faUsers,
  faCog,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faArrowRight,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faCalendar,
  faClock,
  faMapMarkerAlt,
  faEnvelope,
  faPhone,
  faSync,
  faFilter,
  faSort,
  faSave,
  faBan,
  faSignOutAlt,
  faSignInAlt,
  faEyeSlash,
  faUserCog,
  faUserEdit,
  faUserPlus,
  faUserMinus,
  faUserCheck,
  faUserTimes,
  faUserShield,
  faUserGraduate,
  faUserTie,
  faUserFriends,
  faUserSecret,
  faUserNinja,
  faUserAstronaut,
  faUserDoctor,
  faUserNurse,
  faUserGear,
  faCopyright,
  faLinkedin,
  faPalette,
  faTree,
  faBuilding,
  faSeedling,
  faMusic,
  faSnowflake,
  faEllipsisVertical,
  faAnglesLeft,
  faAngleLeft,
  faAngleRight,
  faAnglesRight,
  faDollarSign,
  faCreditCard,
  faCoins
};

// Icon mapping for easy access
export const ICON_MAP = {
  // Navigation
  back: faArrowLeft,
  home: faHome,
  menu: faBars,
  close: faTimes,

  // Actions
  edit: faEdit,
  delete: faTrash,
  add: faPlus,
  save: faSave,
  cancel: faBan,
  search: faSearch,
  filter: faFilter,
  sort: faSort,
  view: faEye,

  // Status
  check: faCheck,
  warning: faExclamationTriangle,
  error: faExclamationTriangle,
  info: faInfoCircle,
  success: faCheck,

  // User/Auth
  user: faUser,
  users: faUsers,
  logout: faSignOutAlt,
  login: faSignInAlt,
  eye: faEye,
  'eye-slash': faEyeSlash,

  // Data
  calendar: faCalendar,
  clock: faClock,
  location: faMapMarkerAlt,
  email: faEnvelope,
  phone: faPhone,

  // UI
  'chevron-down': faChevronDown,
  'chevron-up': faChevronUp,
  'chevron-left': faChevronLeft,
  'chevron-right': faChevronRight,
  'arrow-left': faArrowLeft,
  'arrow-right': faArrowRight,

  // Theme
  sun: faSun,
  moon: faMoon,

  // Refresh/Update
  refresh: faSync,
  sync: faSync,
  update: faSync,

  // Admin
  settings: faCog,
  'user-cog': faUserCog,
  'user-edit': faUserEdit,
  'user-plus': faUserPlus,
  'user-minus': faUserMinus,
  'user-check': faUserCheck,
  'user-times': faUserTimes,
  'user-shield': faUserShield,
  'user-graduate': faUserGraduate,
  'user-tie': faUserTie,
  'user-friends': faUserFriends,
  'user-secret': faUserSecret,
  'user-ninja': faUserNinja,
  'user-astronaut': faUserAstronaut,
  'user-doctor': faUserDoctor,
  'user-nurse': faUserNurse,
  'user-teacher': faUserGear,
  'copyright': faCopyright,
  'linkedin': faLinkedin,
  'palette': faPalette,
  'tree': faTree,
  'building': faBuilding,
  'seedling': faSeedling,
  'music': faMusic,
  'snowflake': faSnowflake,
  'ellipsis-vertical': faEllipsisVertical,
  'angles-left': faAnglesLeft,
  'angle-left': faAngleLeft,
  'angle-right': faAngleRight,
  'angles-right': faAnglesRight,
  'dollar-sign': faDollarSign,
  'credit-card': faCreditCard,
  'coins': faCoins
} as const;

// Type for icon names
export type IconType = keyof typeof ICON_MAP;
