--
-- VERSION 1.0.0
--
--
-- VERSION     REQUEST NRO    USER            DATE             CHANGES
-- ----------- -------------- --------------- ---------------- ----------------
-- 1.0.0                      JMVELEZ         15/01/2025       Creación indexes tabla clientes
-- ----------- -------------- --------------- ---------------- ----------------
--
--
-- OBJECT TYPE: INDEXES
-- OBJECT NAME: CL_TCLIE_INDEXES
-- DESCRIPTION: Performance indexes for CL_TCLIE table
--

-- Drop existing indexes if they exist
DROP INDEX IF EXISTS CL_ICLIE_PERS;
DROP INDEX IF EXISTS CL_ICLIE_USER;
DROP INDEX IF EXISTS CL_ICLIE_CODE;
DROP INDEX IF EXISTS CL_ICLIE_TYPE;
DROP INDEX IF EXISTS CL_ICLIE_CATEGORY;
DROP INDEX IF EXISTS CL_ICLIE_STATUS;
DROP INDEX IF EXISTS CL_ICLIE_ACTIVE;
DROP INDEX IF EXISTS CL_ICLIE_COMPANY_NAME;
DROP INDEX IF EXISTS CL_ICLIE_TAX_ID;
DROP INDEX IF EXISTS CL_ICLIE_RATING;
DROP INDEX IF EXISTS CL_ICLIE_SOURCE;

-- Create indexes
CREATE INDEX CL_ICLIE_PERS ON CL_TCLIE(clie_pers);
CREATE INDEX CL_ICLIE_USER ON CL_TCLIE(clie_user);
CREATE INDEX CL_ICLIE_CODE ON CL_TCLIE(clie_client_code);
CREATE INDEX CL_ICLIE_TYPE ON CL_TCLIE(clie_type);
CREATE INDEX CL_ICLIE_CATEGORY ON CL_TCLIE(clie_category);
CREATE INDEX CL_ICLIE_STATUS ON CL_TCLIE(clie_status);
CREATE INDEX CL_ICLIE_ACTIVE ON CL_TCLIE(clie_is_active);
CREATE INDEX CL_ICLIE_COMPANY_NAME ON CL_TCLIE(clie_company_name);
CREATE INDEX CL_ICLIE_TAX_ID ON CL_TCLIE(clie_tax_id);
CREATE INDEX CL_ICLIE_RATING ON CL_TCLIE(clie_rating);
CREATE INDEX CL_ICLIE_SOURCE ON CL_TCLIE(clie_source); 