--
-- VERSION 1.0.0
--
--
-- VERSION     REQUEST NRO    USER            DATE             CHANGES
-- ----------- -------------- --------------- ---------------- ----------------
-- 1.0.0                      JMVELEZ         15/01/2025       Creación indexes tabla clientes
-- ----------- -------------- --------------- ---------------- ----------------
--
--
-- OBJECT TYPE: INDEXES
-- OBJECT NAME: CU_TCLIE_INDEXES
-- DESCRIPTION: Performance indexes for CU_TCLIE table
--

-- Drop existing indexes if they exist
DROP INDEX IF EXISTS CU_ICLIE_PERS;
DROP INDEX IF EXISTS CU_ICLIE_USER;
DROP INDEX IF EXISTS CU_ICLIE_CODE;
DROP INDEX IF EXISTS CU_ICLIE_TYPE;
DROP INDEX IF EXISTS CU_ICLIE_CATEGORY;
DROP INDEX IF EXISTS CU_ICLIE_STATUS;
DROP INDEX IF EXISTS CU_ICLIE_ACTIVE;
DROP INDEX IF EXISTS CU_ICLIE_COMPANY_NAME;
DROP INDEX IF EXISTS CU_ICLIE_TAX_ID;
DROP INDEX IF EXISTS CU_ICLIE_RATING;
DROP INDEX IF EXISTS CU_ICLIE_SOURCE;

-- Create indexes
CREATE INDEX CU_ICLIE_PERS ON CU_TCLIE(clie_pers);
CREATE INDEX CU_ICLIE_USER ON CU_TCLIE(clie_user);
CREATE INDEX CU_ICLIE_CODE ON CU_TCLIE(clie_client_code);
CREATE INDEX CU_ICLIE_TYPE ON CU_TCLIE(clie_type);
CREATE INDEX CU_ICLIE_CATEGORY ON CU_TCLIE(clie_category);
CREATE INDEX CU_ICLIE_STATUS ON CU_TCLIE(clie_status);
CREATE INDEX CU_ICLIE_ACTIVE ON CU_TCLIE(clie_is_active);
CREATE INDEX CU_ICLIE_COMPANY_NAME ON CU_TCLIE(clie_company_name);
CREATE INDEX CU_ICLIE_TAX_ID ON CU_TCLIE(clie_tax_id);
CREATE INDEX CU_ICLIE_RATING ON CU_TCLIE(clie_rating);
CREATE INDEX CU_ICLIE_SOURCE ON CU_TCLIE(clie_source); 