--
-- VERSION 1.0.0
--
--
-- VERSION     REQUEST NRO    USER            DATE             CHANGES
-- ----------- -------------- --------------- ---------------- ----------------
-- 1.0.0                      JMVELEZ         15/01/2025       Creación indexes tabla empleados
-- ----------- -------------- --------------- ---------------- ----------------
--
--
-- OBJECT TYPE: INDEXES
-- OBJECT NAME: GE_TEMPL_INDEXES
-- DESCRIPTION: Performance indexes for GE_TEMPL table
--

-- Drop existing indexes if they exist
DROP INDEX IF EXISTS GE_IEMPL_PERS;
DROP INDEX IF EXISTS GE_IEMPL_CODE;
DROP INDEX IF EXISTS GE_IEMPL_POSITION;
DROP INDEX IF EXISTS GE_IEMPL_DEPARTMENT;
DROP INDEX IF EXISTS GE_IEMPL_HIRE_DATE;
DROP INDEX IF EXISTS GE_IEMPL_STATUS;
DROP INDEX IF EXISTS GE_IEMPL_WORK_EMAIL;
DROP INDEX IF EXISTS GE_IEMPL_EMPLOYMENT_TYPE;
DROP INDEX IF EXISTS GE_IEMPL_JOB_LEVEL;
DROP INDEX IF EXISTS GE_IEMPL_WORK_SHIFT;
DROP INDEX IF EXISTS GE_IEMPL_ACTIVE;

-- Create indexes
CREATE INDEX GE_IEMPL_PERS ON GE_TEMPL(empl_pers);
CREATE INDEX GE_IEMPL_POSITION ON GE_TEMPL(empl_position);
CREATE INDEX GE_IEMPL_DEPARTMENT ON GE_TEMPL(empl_department);
CREATE INDEX GE_IEMPL_HIRE_DATE ON GE_TEMPL(empl_hire_date);
CREATE INDEX GE_IEMPL_STATUS ON GE_TEMPL(empl_status);
CREATE INDEX GE_IEMPL_WORK_EMAIL ON GE_TEMPL(empl_work_email);
CREATE INDEX GE_IEMPL_EMPLOYMENT_TYPE ON GE_TEMPL(empl_employment_type);
CREATE INDEX GE_IEMPL_JOB_LEVEL ON GE_TEMPL(empl_job_level);
CREATE INDEX GE_IEMPL_WORK_SHIFT ON GE_TEMPL(empl_work_shift);
CREATE INDEX GE_IEMPL_ACTIVE ON GE_TEMPL(empl_is_active); 