--
-- VERSION 1.0.0
--
--
-- VERSION     REQUEST NRO    USER            DATE             CHANGES
-- ----------- -------------- --------------- ---------------- ----------------
-- 1.0.0                      JMVELEZ         15/01/2025       Creación indexes tabla clientes
-- ----------- -------------- --------------- ---------------- ----------------
--
--
-- OBJECT TYPE: INDEXES
-- OBJECT NAME: GE_TCLIE_INDEXES
-- DESCRIPTION: Performance indexes for GE_TCLIE table
--

-- Drop existing indexes if they exist
DROP INDEX IF EXISTS GE_ICLIE_PERS;
DROP INDEX IF EXISTS GE_ICLIE_USER;
DROP INDEX IF EXISTS GE_ICLIE_CODE;
DROP INDEX IF EXISTS GE_ICLIE_TYPE;
DROP INDEX IF EXISTS GE_ICLIE_CATEGORY;
DROP INDEX IF EXISTS GE_ICLIE_STATUS;
DROP INDEX IF EXISTS GE_ICLIE_ACTIVE;
DROP INDEX IF EXISTS GE_ICLIE_COMPANY_NAME;
DROP INDEX IF EXISTS GE_ICLIE_TAX_ID;
DROP INDEX IF EXISTS GE_ICLIE_RATING;
DROP INDEX IF EXISTS GE_ICLIE_SOURCE;

-- Create indexes
CREATE INDEX GE_ICLIE_PERS ON GE_TCLIE(clie_pers);
CREATE INDEX GE_ICLIE_USER ON GE_TCLIE(clie_user);
CREATE INDEX GE_ICLIE_TYPE ON GE_TCLIE(clie_type);
CREATE INDEX GE_ICLIE_CATEGORY ON GE_TCLIE(clie_category);
CREATE INDEX GE_ICLIE_STATUS ON GE_TCLIE(clie_status);
CREATE INDEX GE_ICLIE_ACTIVE ON GE_TCLIE(clie_is_active);
CREATE INDEX GE_ICLIE_COMPANY_NAME ON GE_TCLIE(clie_company_name);
CREATE INDEX GE_ICLIE_TAX_ID ON GE_TCLIE(clie_tax_id);
CREATE INDEX GE_ICLIE_RATING ON GE_TCLIE(clie_rating);
CREATE INDEX GE_ICLIE_SOURCE ON GE_TCLIE(clie_source); 